/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthLayoutImport } from './routes/_authLayout'
import { Route as AuthenticatedInvoicesImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedDashboardImport } from './routes/_authenticated/dashboard'
import { Route as AuthLayoutRegistrationImport } from './routes/_authLayout/registration'
import { Route as AuthLayoutPasswordRecoverImport } from './routes/_authLayout/passwordRecover'
import { Route as AuthLayoutLoginImport } from './routes/_authLayout/login'
import { Route as AuthLayoutRegistrationIndexImport } from './routes/_authLayout/registration/index'
import { Route as AuthLayoutRegistrationValidateImport } from './routes/_authLayout/registration/validate'
import { Route as AuthLayoutRegistrationUserImport } from './routes/_authLayout/registration/user'
import { Route as AuthLayoutRegistrationCompanyImport } from './routes/_authLayout/registration/company'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutRoute = AuthLayoutImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AuthenticatedInvoicesRoute = AuthenticatedInvoicesImport.update({
  path: '/invoices',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedDashboardRoute = AuthenticatedDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthLayoutRegistrationRoute = AuthLayoutRegistrationImport.update({
  path: '/registration',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutPasswordRecoverRoute = AuthLayoutPasswordRecoverImport.update({
  path: '/passwordRecover',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutLoginRoute = AuthLayoutLoginImport.update({
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutRegistrationIndexRoute =
  AuthLayoutRegistrationIndexImport.update({
    path: '/',
    getParentRoute: () => AuthLayoutRegistrationRoute,
  } as any)

const AuthLayoutRegistrationValidateRoute =
  AuthLayoutRegistrationValidateImport.update({
    path: '/validate',
    getParentRoute: () => AuthLayoutRegistrationRoute,
  } as any)

const AuthLayoutRegistrationUserRoute = AuthLayoutRegistrationUserImport.update(
  {
    path: '/user',
    getParentRoute: () => AuthLayoutRegistrationRoute,
  } as any,
)

const AuthLayoutRegistrationCompanyRoute =
  AuthLayoutRegistrationCompanyImport.update({
    path: '/company',
    getParentRoute: () => AuthLayoutRegistrationRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/_authLayout/login': {
      id: '/_authLayout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLayoutLoginImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_authLayout/passwordRecover': {
      id: '/_authLayout/passwordRecover'
      path: '/passwordRecover'
      fullPath: '/passwordRecover'
      preLoaderRoute: typeof AuthLayoutPasswordRecoverImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_authLayout/registration': {
      id: '/_authLayout/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof AuthLayoutRegistrationImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authLayout/registration/company': {
      id: '/_authLayout/registration/company'
      path: '/company'
      fullPath: '/registration/company'
      preLoaderRoute: typeof AuthLayoutRegistrationCompanyImport
      parentRoute: typeof AuthLayoutRegistrationImport
    }
    '/_authLayout/registration/user': {
      id: '/_authLayout/registration/user'
      path: '/user'
      fullPath: '/registration/user'
      preLoaderRoute: typeof AuthLayoutRegistrationUserImport
      parentRoute: typeof AuthLayoutRegistrationImport
    }
    '/_authLayout/registration/validate': {
      id: '/_authLayout/registration/validate'
      path: '/validate'
      fullPath: '/registration/validate'
      preLoaderRoute: typeof AuthLayoutRegistrationValidateImport
      parentRoute: typeof AuthLayoutRegistrationImport
    }
    '/_authLayout/registration/': {
      id: '/_authLayout/registration/'
      path: '/'
      fullPath: '/registration/'
      preLoaderRoute: typeof AuthLayoutRegistrationIndexImport
      parentRoute: typeof AuthLayoutRegistrationImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AuthLayoutRoute: AuthLayoutRoute.addChildren({
    AuthLayoutLoginRoute,
    AuthLayoutPasswordRecoverRoute,
    AuthLayoutRegistrationRoute: AuthLayoutRegistrationRoute.addChildren({
      AuthLayoutRegistrationCompanyRoute,
      AuthLayoutRegistrationUserRoute,
      AuthLayoutRegistrationValidateRoute,
      AuthLayoutRegistrationIndexRoute,
    }),
  }),
  AuthenticatedRoute: AuthenticatedRoute.addChildren({
    AuthenticatedDashboardRoute,
    AuthenticatedInvoicesRoute,
  }),
  AboutLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authLayout",
        "/_authenticated",
        "/about"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/_authLayout": {
      "filePath": "_authLayout.tsx",
      "children": [
        "/_authLayout/login",
        "/_authLayout/passwordRecover",
        "/_authLayout/registration"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/dashboard",
        "/_authenticated/invoices"
      ]
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/_authLayout/login": {
      "filePath": "_authLayout/login.tsx",
      "parent": "/_authLayout"
    },
    "/_authLayout/passwordRecover": {
      "filePath": "_authLayout/passwordRecover.tsx",
      "parent": "/_authLayout"
    },
    "/_authLayout/registration": {
      "filePath": "_authLayout/registration.tsx",
      "parent": "/_authLayout",
      "children": [
        "/_authLayout/registration/company",
        "/_authLayout/registration/user",
        "/_authLayout/registration/validate",
        "/_authLayout/registration/"
      ]
    },
    "/_authenticated/dashboard": {
      "filePath": "_authenticated/dashboard.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/invoices": {
      "filePath": "_authenticated/invoices.tsx",
      "parent": "/_authenticated"
    },
    "/_authLayout/registration/company": {
      "filePath": "_authLayout/registration/company.tsx",
      "parent": "/_authLayout/registration"
    },
    "/_authLayout/registration/user": {
      "filePath": "_authLayout/registration/user.tsx",
      "parent": "/_authLayout/registration"
    },
    "/_authLayout/registration/validate": {
      "filePath": "_authLayout/registration/validate.tsx",
      "parent": "/_authLayout/registration"
    },
    "/_authLayout/registration/": {
      "filePath": "_authLayout/registration/index.tsx",
      "parent": "/_authLayout/registration"
    }
  }
}
ROUTE_MANIFEST_END */
